// TRANSACTIONS.
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS'
export const HANDLE_CHANGE_DESCRIPTION = 'HANDLE_CHANGE_DESCRIPTION'
export const CREATE_TRANSACTION_ERROR = 'CREATE_TRANSACTION_ERROR'

// USER.
// Register.
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
// Login.
export const LOGIN_USER = 'LOGIN_USER'
