export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS'
export const HANDLE_CHANGE_DESCRIPTION = 'HANDLE_CHANGE_DESCRIPTION'
export const CREATE_TRANSACTION_FAILURE = 'CREATE_TRANSACTION_FAILURE'
