// TRANSACTIONS.
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS'
export const HANDLE_CHANGE_DESCRIPTION = 'HANDLE_CHANGE_DESCRIPTION'
export const CREATE_TRANSACTION_ERROR = 'CREATE_TRANSACTION_ERROR'

// USER.
// Register.
export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'
// Login.
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
// Data.
export const GET_USER_DATA = 'GET_USER_DATA'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_ERROR = 'GET_USER_DATA_ERROR'

// HISTORY.
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS'
